# LuckyD Browser -- one-command release: bump version, build, install locally,
# publish to GitHub Releases, and make sure existing installs auto-update.
#
#   powershell -NoProfile -ExecutionPolicy Bypass -File browser\installer\release.ps1
#
# Optional:
#   -Bump major|minor|patch   (default: patch)
#   -Notes "custom release notes"   (default: auto-generated by gh)
#   -SkipPublish               (build + install locally only, skip git/GitHub)
#
# What it does, in order:
#   1. Bumps the version number in the 3 places that must agree:
#        browser\__init__.py, browser\version_info.txt, browser\installer\LuckyDBrowser.iss
#      (a NEW version number is required for the in-app updater to ever
#      notice a release -- publishing the same version again is invisible
#      to installed users, since updater.py only fires on a strictly-newer
#      version comparison).
#   2. Kills any running LuckyD Browser process (so the rebuild isn't
#      blocked by locked files).
#   3. Rebuilds with PyInstaller --clean + compiles the Inno Setup installer
#      (reuses browser\installer\build_installer.ps1).
#   4. Copies the freshly built installer to the Desktop, removing any
#      older LuckyDBrowserSetup-*.exe there first so there is only ever
#      ONE installer on the Desktop and it is unambiguously the latest.
#   5. Commits the version bump, tags it vX.Y.Z, and pushes both to GitHub.
#   6. Publishes a GitHub Release for that tag with the installer .exe
#      attached as a release asset (this is what browser_core/updater.py
#      polls for -- GET /repos/<repo>/releases/latest -- so every installed
#      copy will offer this update automatically ~8s after their next launch).

param(
    [ValidateSet('major', 'minor', 'patch')]
    [string]$Bump = 'patch',
    [string]$Notes = '',
    [switch]$SkipPublish
)

$ErrorActionPreference = 'Stop'

$installerDir = $PSScriptRoot                                   # ...\browser\installer
$browserDir   = Split-Path $installerDir -Parent                 # ...\browser
$repoRoot     = Split-Path $browserDir -Parent                   # ...\coding-agent
$desktopDir   = Split-Path $repoRoot -Parent                     # ...\Desktop (repo sits directly on Desktop)

$initPy       = Join-Path $browserDir '__init__.py'
$versionInfo  = Join-Path $browserDir 'version_info.txt'
$issScript    = Join-Path $installerDir 'LuckyDBrowser.iss'
$ghRepo       = 'Dylanchess0320/LuckyD-Browser'

function Write-Step($msg) { Write-Host "" ; Write-Host "== $msg ==" -ForegroundColor Cyan }
function Write-Ok($msg)   { Write-Host "  OK: $msg" -ForegroundColor Green }
function Write-Warn2($msg) { Write-Host "  WARNING: $msg" -ForegroundColor Yellow }

# ---- 1. Bump version -------------------------------------------------------
Write-Step 'Bumping version'

$initContent = Get-Content $initPy -Raw
if ($initContent -notmatch '__version__\s*=\s*"([^"]+)"') {
    throw "Could not find __version__ in $initPy"
}
$current = $Matches[1]
$parts = $current.Split('.') | ForEach-Object { [int]$_ }
while ($parts.Count -lt 3) { $parts += 0 }
switch ($Bump) {
    'major' { $parts[0]++; $parts[1] = 0; $parts[2] = 0 }
    'minor' { $parts[1]++; $parts[2] = 0 }
    'patch' { $parts[2]++ }
}
$new = "$($parts[0]).$($parts[1]).$($parts[2])"
$tag = "v$new"
Write-Ok "$current -> $new"

# __init__.py
$initContent = $initContent -replace '__version__\s*=\s*"[^"]*"', "__version__ = `"$new`""
Set-Content -Path $initPy -Value $initContent -NoNewline -Encoding UTF8
Write-Ok "browser\__init__.py"

# version_info.txt (PyInstaller Windows version resource)
$vi = Get-Content $versionInfo -Raw
$vi = $vi -replace 'filevers=\([^)]*\)', "filevers=($($parts[0]), $($parts[1]), $($parts[2]), 0)"
$vi = $vi -replace 'prodvers=\([^)]*\)', "prodvers=($($parts[0]), $($parts[1]), $($parts[2]), 0)"
$vi = $vi -replace "StringStruct\('FileVersion', '[^']*'\)", "StringStruct('FileVersion', '$new.0')"
$vi = $vi -replace "StringStruct\('ProductVersion', '[^']*'\)", "StringStruct('ProductVersion', '$new.0')"
Set-Content -Path $versionInfo -Value $vi -NoNewline -Encoding UTF8
Write-Ok "browser\version_info.txt"

# LuckyDBrowser.iss (Inno Setup script)
$iss = Get-Content $issScript -Raw
$iss = $iss -replace '#define AppVersion\s+"[^"]*"', "#define AppVersion   `"$new`""
$iss = $iss -replace 'VersionInfoVersion=\S*', "VersionInfoVersion=$new.0"
$iss = $iss -replace 'VersionInfoProductVersion=\S*', "VersionInfoProductVersion=$new.0"
$iss = $iss -replace 'OutputBaseFilename=\S*', "OutputBaseFilename=LuckyDBrowserSetup-$new"
Set-Content -Path $issScript -Value $iss -Encoding UTF8
Write-Ok "browser\installer\LuckyDBrowser.iss"

# ---- 2. Close any running instance so the rebuild isn't file-locked -------
Write-Step 'Closing any running LuckyD Browser instance'
foreach ($proc in @('LuckyDBrowser', 'QtWebEngineProcess')) {
    Get-Process -Name $proc -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
}
Write-Ok 'done'

# ---- 3. Build (PyInstaller --clean + Inno Setup) ---------------------------
Write-Step 'Building installer (PyInstaller + Inno Setup)'
& (Join-Path $installerDir 'build_installer.ps1')
if ($LASTEXITCODE -and $LASTEXITCODE -ne 0) { throw "build_installer.ps1 failed (exit $LASTEXITCODE)" }

$builtInstaller = Get-ChildItem (Join-Path $installerDir "output\LuckyDBrowserSetup-$new.exe") -ErrorAction SilentlyContinue
if (-not $builtInstaller) { throw "Expected output\LuckyDBrowserSetup-$new.exe was not produced" }
Write-Ok "$($builtInstaller.Name)  ($('{0:N1}' -f ($builtInstaller.Length / 1MB)) MB)"

# Archive older installer builds so output\ doesn't accumulate clutter.
$oldBuildsDir = Join-Path $installerDir 'output\old_builds'
New-Item -ItemType Directory -Path $oldBuildsDir -Force | Out-Null
Get-ChildItem (Join-Path $installerDir 'output\*.exe') |
    Where-Object { $_.Name -ne $builtInstaller.Name } |
    ForEach-Object { Move-Item $_.FullName (Join-Path $oldBuildsDir $_.Name) -Force }

# ---- 4. Put the one, unambiguous, up-to-date installer on the Desktop -----
Write-Step 'Updating Desktop copy'
Get-ChildItem (Join-Path $desktopDir 'LuckyDBrowserSetup-*.exe') -ErrorAction SilentlyContinue |
    Remove-Item -Force -ErrorAction SilentlyContinue
Copy-Item $builtInstaller.FullName -Destination (Join-Path $desktopDir $builtInstaller.Name) -Force
Write-Ok "Desktop\$($builtInstaller.Name)"

if ($SkipPublish) {
    Write-Host ""
    Write-Host "-SkipPublish set -- local build done, GitHub publish skipped." -ForegroundColor Yellow
    exit 0
}

# ---- 5. Commit, tag, push --------------------------------------------------
Write-Step 'Committing version bump and tagging'
Push-Location $repoRoot
try {
    git add -- 'browser/__init__.py' 'browser/version_info.txt' 'browser/installer/LuckyDBrowser.iss'
    git commit -m "Release $tag" | Out-Null
    git tag -a $tag -m "LuckyD Browser $new"
    Write-Ok "committed + tagged $tag"

    try {
        git push origin HEAD
        git push origin $tag
        Write-Ok 'pushed commit + tag to origin'
    } catch {
        Write-Warn2 "git push failed: $_"
        Write-Warn2 'The GitHub release will still be created below, but push the commit/tag manually afterward (git push origin HEAD --tags) so the source matches the release.'
    }
} finally {
    Pop-Location
}

# ---- 6. Publish the GitHub Release with the installer attached ------------
Write-Step 'Publishing GitHub Release'

$gh = Get-Command gh -ErrorAction SilentlyContinue
if (-not $gh) {
    Write-Warn2 'GitHub CLI (gh) is not installed -- cannot publish automatically.'
    Write-Warn2 'Install it (winget install --id GitHub.cli) then run:'
    Write-Warn2 "  gh release create $tag `"$($builtInstaller.FullName)`" --repo $ghRepo --title `"LuckyD Browser $new`" --generate-notes"
    exit 1
}

$ghAuth = & gh auth status 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Warn2 'GitHub CLI is not authenticated. Run: gh auth login'
    Write-Warn2 "Then re-run: gh release create $tag `"$($builtInstaller.FullName)`" --repo $ghRepo --title `"LuckyD Browser $new`" --generate-notes"
    exit 1
}

$ghArgs = @(
    'release', 'create', $tag,
    $builtInstaller.FullName,
    '--repo', $ghRepo,
    '--title', "LuckyD Browser $new"
)
if ($Notes) { $ghArgs += @('--notes', $Notes) } else { $ghArgs += '--generate-notes' }

$releaseUrl = & gh @ghArgs
if ($LASTEXITCODE -ne 0) { throw "gh release create failed (exit $LASTEXITCODE)" }

Write-Ok "published: $releaseUrl"

Write-Host ""
Write-Host "=================================================================" -ForegroundColor Green
Write-Host " LuckyD Browser $new is live." -ForegroundColor Green
Write-Host " Desktop installer : Desktop\$($builtInstaller.Name)" -ForegroundColor Green
Write-Host " GitHub release    : $releaseUrl" -ForegroundColor Green
Write-Host " Existing installs will be offered this update automatically" -ForegroundColor Green
Write-Host " (checked ~8s after launch, since $new > their current version)." -ForegroundColor Green
Write-Host "=================================================================" -ForegroundColor Green
